---
- hosts: PreProdNodetest
  user: root
  vars:
    was_app_name: DPZ_test
    owner: was6tst
    group: was6group
    default_port: 21020
    path: /data/dpz/{{ was_app_name }}

    dataSources:
    - authDataAlias: TEST/JDPZ500
      authDataPassword: wait
      dataTruncation: 'false'
      databaseName: TESTGFDI
      dateFormat: iso
      jndiName: jdbc/DPZ_RC
      libraries: '*LIBL'
      name: DPZ500
      naming: system
      serverName: test.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JDPZ500
      webSphereDefaultIsolationLevel: '2'
    - authDataAlias: udbitst97/dbdpztst
      authDataPassword: dpztest123
      clientRerouteAlternatePortNumber: '50004'
      clientRerouteAlternateServerName: db2-test04.jablux.gfdi.be
      currentSchema: INTG
      databaseName: INT500
      driverType: '4'
      jndiName: jdbc/INTG_RC
      name: INTGDPZ500
      portNumber: '50004'
      serverName: db2-test03.jablux.gfdi.be
      typeds: universal
      user: dbdpztst
      webSphereDefaultIsolationLevel: '2'
    
    mqjms:
    - authDataAlias: TEST/JDPZ500
      authDataPassword: wait
      jndiName: jms/DPZ_QCF_RC
      name: DPZ_QCF_500
      qmgrHostname: ref.ref.cpc998.be
      qmgrName: QM.500
      qmgrPortNumber: '14500'
      qmgrSvrconnChannel: SYSTEM.DEF.SVRCONN

    resourceEnvEntries:
    - customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/server-config.xml"
      jndiName: config/ConfigServer
      name: ConfigServer
    - customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/careunit.properties"
      jndiName: config/CareUnitConfig
      name: CareUnitConfig
    - customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/wssecurityin.properties"
      jndiName: config/CertificateConfig
      name: CertificateConfig
    - customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/wssecurityout.properties"
      jndiName: config/KeystoreConfig
      name: KeystoreConfig
    - customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/flowList.properties"
      jndiName: config/FlowListConfig
      name: FlowListConfig

    resourceFiles:
    - file/DPZ/careunit.properties
    - file/DPZ/flowList.properties
    - file/DPZ/server-config.xml
    - file/DPZ/wssecurityin.properties
    - file/DPZ/wssecurityout.properties

    systemProperties:
    - name: com.ibm.websphere.webservices.DisableIBMJAXWSEngine
      value: true
    - name: java.security.debug
      value: certpath
    - name: mule.verbose.exceptions
      value: true
    - name: intg.jndi.prefix
      value: jndi

  roles:
  - base_was
