---
- hosts: PreProdNodetest
  user: root
  vars:
    was_app_name: MYCARENET_test
    owner: was6tst
    group: was6group
    default_port: 21120
    path: /data/mycarenet/{{ was_app_name }}

    dataSources:
    - authDataAlias: TEST/JCARE500
      authDataPassword: wait
      dataTruncation: 'false'
      databaseName: TESTGFDI
      dateFormat: iso
      jndiName: jdbc/CARENET_AS400_RC
      libraries: '*LIBL'
      name: AS400MCT_500
      naming: system
      serverName: test.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JCARE500
    - authDataAlias: udbich4597/dbmcttst
      authDataPassword: tst20120410
      clientRerouteAlternatePortNumber: '50020'
      clientRerouteAlternateServerName: db2-nippin02.jablux.gfdi.be
      currentSchema: CARE
      databaseName: MCT500
      driverType: '4'
      jndiName: jdbc/CARENET_LINUX_RC
      name: LNXMCT_500
      portNumber: '50020'
      serverName: db2-nippin01.jablux.gfdi.be
      typeds: universal
      user: dbmcttst
      webSphereDefaultIsolationLevel: '2'
      connectionPool:
        maxConnections: 100
        minConnections: 5

    mqjms:
    - authDataAlias: TEST/JCARE500
      authDataPassword: WAIT
      jndiName: jms/QL.INTG_MC_IN
      name: QL.INTG_MC_IN
      qmgrHostname: ref.ref.cpc998.be
      qmgrName: QM.500
      qmgrPortNumber: '14500'
      qmgrSvrconnChannel: SYSTEM.DEF.SVRCONN

    resourceEnvEntries:
    - customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/carenet.properties"
      jndiName: config/CarenetConfig
      name: ConfigServer

    systemProperties:
     - name: spring.profiles.active
       value: was
     - name: file.encoding
       value: ISO-8859-15
     - name: mule.encoding
       value: ISO-8859-15

    resourceFiles:
    - files/MYCARENET/carenet.properties

  roles:
  - base_was
