---
- hosts: ProdNode_AIRBUS_200G_RFND
  user: root
  vars:
    was_app_name: INTG_200
    default_port: 21160
    path: /data/intg/{{ was_app_name }}
    group: was6group
    owner: was6u200

    vhost: RfndProd{{ dc }}_vhost

    systemProperties:
    - name: client.encoding.override
      value: 'UTF-8'
    - name: file.encoding
      value: 'UTF-8'
    - name: intg.jndi.prefix
      value: jndi
    - name: net.sf.ehcache.skipUpdateCheck
      value: true

    dataSources:
    - authDataAlias: udbiint297/dbint200
      authDataPassword: 200ljfqk
      clientRerouteAlternateServerName: s298lp2dbrf02.jablux.cpc998.be
      clientRerouteAlternatePortNumber: 50004
      currentSchema: INTG
      enableSeamlessFailover: 1
      databaseName: RFN200
      driverType: '4'
      jndiName: jdbc/INTG_200
      name: INTG_200
      portNumber: '50004'
      serverName: s298lp1dbrf02.jablux.cpc998.be
      typeds: universal
      user: dbint200
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: AIRBUS/INTG200
      authDataPassword: rq200vni
      dataTruncation: 'false'
      databaseName: AIRBUS
      dateFormat: iso
      extendedDynamic: 'false'
      jndiName: jdbc/JADE2_200
      libraries: '*LIBL'
      name: JADE2_200
      naming: system
      package: DSJ2200
      packageCriteria: select
      packageLibrary: JADEBUS200
      serverName: airbus.jablux.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: INTG200
      connectionPool:
         connectionTimeout: 30
         maxConnections: 50
         minConnections: 15
         reapTime: 300
         agedTimeout: 0 

  roles:
  - base_was