---
- hosts: RefNode_REF_500A_FLUX
  user: root
  vars:
    was_app_name: DMG_500_MBR1
    was_cluster_name: DMG_500
    default_port: 21080
    owner: was6u500
    group: was6group
    path: /data/dmg/{{ was_app_name }}

    vhost: DMG_500_vhost
    host_aliases:
    - hostname: dmg5xx-ref.ref.cpc998.be
      port: 443
    - hostname: s598lr2wsrp01.ref.cpc998.be
      port: 443
    - hostname: s598lr2wsrp02.ref.cpc998.be
      port: 443
    - hostname: s598lr2wsfl01.ref.cpc998.be
      port: 21080
    - hostname: s598lr2wsfl02.ref.cpc998.be
      port: 21080
    - hostname: s598lr2wsfl01.ref.cpc998.be
      port: 21081
    - hostname: s598lr2wsfl02.ref.cpc998.be
      port: 21081

    dataSources:
    - authDataAlias: REF/JCARE500
      authDataPassword: MAQID31
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      jndiName: jdbc/DMG_AS400_RC
      libraries: '*LIBL'
      name: AS400GDMG_500
      naming: system
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JCARE500
      connectionPool:
         maxConnections: 50
         minConnections: 5

    - authDataAlias: udbidmg597/dbmct500
      authDataPassword: 19jun091541
      clientProgramName: DMG
      clientRerouteAlternatePortNumber: '50004'
      clientRerouteAlternateServerName: s000lr2dbfl02.ref.cpc998.be
      currentSchema: CARE
      enableSeamlessFailover: 1
      databaseName: MCT500
      driverType: 4
      jndiName: jdbc/DMG_LINUX_RC
      name: LNXGDMG_500
      portNumber: 50004
      serverName: s000lr2dbfl01.ref.cpc998.be
      typeds: universal
      user: dbmct500
      webSphereDefaultIsolationLevel: 2
      statementCacheSize: 500
      connectionPool:
        maxConnections: 50
        minConnections: 5

    jmscf:
    - jndiName: jms/mqIIBConnectionFactory 
      qmgrName: RQM5FL1
      qmgrSvrconnChannel: MTEAM.CLIENT.SVRCONN
      connectionNameList: s598lr2iibfl01.ref.cpc998.be(16500),s598lr2iibfl02.ref.cpc998.be(16500)
      authDataAlias: JMSCF/uqmfl500
      user: uqmfl500
      authDataPassword: Welcome01
      name: DMG_mqConnectionFactory
      connectionPool:
        minConnections: 20
        maxConnections: 80

    jmsq:
    - jndiName: jms/DMG_CONSULT_IN
      queueName: QA.DMG.CONSULT.IN
      advancedProperties:
        useRFH2: 'false'
    - jndiName: jms/DMG_CONSULT_OUT
      queueName: QA.DMG.CONSULT.OUT
    - jndiName: jms/DMG_CONSULT_LIST_IN
      queueName: QA.DMG.CONSULT.LIST.IN
      advancedProperties:
        useRFH2: 'false'
    - jndiName: jms/DMG_CONSULT_LIST_OUT
      queueName: QA.DMG.CONSULT.LIST.OUT
    - jndiName: jms/DMG_NOTIFY_IN
      queueName: QA.DMG.NOTIFY.IN
      advancedProperties:
        useRFH2: 'false'
    - jndiName: jms/DMG_NOTIFY_OUT
      queueName: QA.DMG.NOTIFY.OUT
    - jndiName: jms/DMG_CLOSURE_OUT
      queueName: QA.DMG.CLOSURE.OUT
    - jndiName: jms/DMG_PROLONG_OUT
      queueName: QA.DMG.PROLONG.OUT
    - jndiName: jms/DMG_SUBSCRIPTION_IN
      queueName: QA.DMG.SUBSCRIPTION.IN
      advancedProperties:
        useRFH2: 'false'
    - jndiName: jms/DMG_SUBSCRIPTION_OUT
      queueName: QA.DMG.SUBSCRIPTION.OUT

    resourceEnvEntries:
    - name: DMGConfig
      jndiName: config/dmgConfig
      customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/dmg.properties"

    systemProperties:
    - name: spring.profiles.active
      value: was
    - name: file.encoding
      value: ISO-8859-15
    - name: mule.encoding
      value: ISO-8859-15

    resourceFiles:
    - files/DMG/dmg.properties

  roles:
  - base_was
