---
- hosts: RefNode_REF_500A_FLUX
  user: root
  vars:
    was_app_name: SAMDB_500_MBR1
    was_cluster_name: SAMDB_500
    default_port: 21240
    owner: was6u500
    group: was6group
    path: /data/samdb/{{ was_app_name }}

    host_aliases:
    - hostname: samdb5xx-ref.ref.cpc998.be
      port: 80
    - hostname: samdb5xx-ref.ref.cpc998.be
      port: 443
    - hostname: s598lr2wsfl02.ref.cpc998.be
      port: 21240
    - hostname: s598lr2wsfl02.ref.cpc998.be
      port: 21241
    - hostname: s598lr2wsfl01.ref.cpc998.be
      port: 21240
    - hostname: s598lr2wsfl01.ref.cpc998.be
      port: 21241
    - hostname: s598lr2wsrp01.ref.cpc998.be
      port: 80
    - hostname: s598lr2wsrp02.ref.cpc998.be
      port: 80

    dataSources:
    - authDataAlias: REF/JCARE500
      authDataPassword: MAQID31
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      jndiName: jdbc/DBSAM_AS400_RC
      libraries: '*LIBL'
      name: AS400DBSAM_5xx
      naming: system
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JCARE500
      connectionPool:
         maxConnections: 50
         minConnections: 5

    resourceEnvEntries:
    - name: SamdbRessourceConfig
      jndiName: config/dbsamConfig
      customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/ch4_dbsam.properties"

    resourceFiles:
    - files/SAMDB/ch4_dbsam.properties

  roles:
  - base_was
