---
- hosts: RefNode_REF_500I_RFND
  user: root
  vars:
    dataSources:
    - BMD500
    default_port: 21200
    group: was6group
    owner: was6u500
    path: /data/bmd/{{ was_app_name }}
    systemProperties:
    - name: java.net.preferIPv4Stack
      value: true
    - name: java.awt.headless
      value: true
    was_app_name: BMD_500

  roles:
  - base_was