---
- hosts: RefNode_REF_500bC_RFND
  user: root
  vars:
    was_app_name: JADER_500b_MBR1
    was_cluster_name: JADER_500b
    owner: was6u500
    group: was6group
    default_port: 21040
    path: /data/jade/{{ was_app_name }}

    vhost: RfndRef_vhost

    systemProperties:
    - name: jade2.jobs.JADE2_SERVER
      value: true
    - name: jade2.jobs.RFND_GRP500b
      value: true
    - name: net.sf.ehcache.skipUpdateCheck
      value: true
    - name: jade2.jobs.500
      value: true
    - name: jade2.jobs.515
      value: true
    - name: client.encoding.override
      value: 'UTF-8'
    - name: file.encoding
      value: 'UTF-8'

    dataSources:
    - authDataAlias: REF/JRDE500
      authDataPassword: fcnie500
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      jndiName: jdbc/JADE2_500
      libraries: '*LIBL'
      name: JADE2_500
      naming: system
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE500
      extendedDynamic: false
      package: DSJ2500
      packageLibrary: JADEBUS500
      packageCriteria: select
      connectionPool:
         connectionTimeout: 30
         maxConnections: 60
         minConnections: 1
         reapTime: 300
         agedTimeout: 0 

    - authDataAlias: REF/JRDE501
      authDataPassword: nidqf501
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      jndiName: jdbc/JADE2_501
      libraries: '*LIBL'
      name: JADE2_501
      naming: system
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE501
      extendedDynamic: false
      package: DSJ2501
      packageLibrary: JADEBUS501
      packageCriteria: select
      connectionPool:
         connectionTimeout: 30
         maxConnections: 60
         minConnections: 1
         reapTime: 300
         agedTimeout: 0 

    - authDataAlias: REF/JRDE515
      authDataPassword: porkf515
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      jndiName: jdbc/JADE2_515
      libraries: '*LIBL'
      name: JADE2_515
      naming: system
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE515
      extendedDynamic: false
      package: DSJ2515
      packageLibrary: JADEBUS515
      packageCriteria: select
      connectionPool:
         connectionTimeout: 30
         maxConnections: 60
         minConnections: 1
         reapTime: 300
         agedTimeout: 0 

    - authDataAlias: refiorc597/dborc500
      authDataPassword: 500lkjds
      currentSchema: ORC500
      enableSeamlessFailover: 0
      databaseName: RFN500
      driverType: '4'
      jndiName: jdbc/BPE_500
      name: BPE_500
      portNumber: '50004'
      serverName: s598lr2dbrf02.ref.cpc998.be
      typeds: universal
      user: dborc500
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: refiorc597/dborc501
      authDataPassword: 501fdqks
      currentSchema: ORC501
      enableSeamlessFailover: 0
      databaseName: RFN500
      driverType: '4'
      jndiName: jdbc/BPE_501
      name: BPE_501
      portNumber: '50004'
      serverName: s598lr2dbrf02.ref.cpc998.be
      typeds: universal
      user: dborc501
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: refiorc597/dborc515
      authDataPassword: 515lqskj
      currentSchema: ORC515
      enableSeamlessFailover: 0
      databaseName: RFN500
      driverType: '4'
      jndiName: jdbc/BPE_515
      name: BPE_515
      portNumber: '50004'
      serverName: s598lr2dbrf02.ref.cpc998.be
      typeds: universal
      user: dborc515
      webSphereDefaultIsolationLevel: '2'

    directories:
    - '{{ path }}/work/jobs'

  roles:
  - base_was

