---
- hosts: RefNode_REF_200aA_RFND
  user: root
  vars:
    was_app_name: JADER_200a_MBR1
    was_cluster_name: JADER_200a
    owner: was6u200
    group: was6group
    default_port: 21040
    path: /data/jade/{{ was_app_name }}

    vhost: RfndRef_vhost

    systemProperties:
    - name: jade2.jobs.JADE2_SERVER
      value: true
    - name: jade2.jobs.RFND_GRP200a
      value: true
    - name: net.sf.ehcache.skipUpdateCheck
      value: true
    - name: jade2.jobs.203
      value: true
    - name: jade2.jobs.216
      value: true
    - name: jade2.jobs.232
      value: true
    - name: client.encoding.override
      value: 'UTF-8'
    - name: file.encoding
      value: 'UTF-8'

    dataSources:
    - authDataAlias: refiorc297/dborc203
      authDataPassword: 203lzeir
      currentSchema: ORC203
      enableSeamlessFailover: 0
      databaseName: RFN200
      driverType: '4'
      jndiName: jdbc/BPE_203
      name: BPE_203
      portNumber: '50004'
      serverName: s298lr2dbrf02.ref.cpc998.be
      typeds: universal
      user: dborc203
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: refiorc297/dborc216
      authDataPassword: 216pzokv
      currentSchema: ORC216
      enableSeamlessFailover: 0
      databaseName: RFN200
      driverType: '4'
      jndiName: jdbc/BPE_216
      name: BPE_216
      portNumber: '50004'
      serverName: s298lr2dbrf02.ref.cpc998.be
      typeds: universal
      user: dborc216
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: refiorc297/dborc232
      authDataPassword: 232qmlkv
      currentSchema: ORC232
      enableSeamlessFailover: 0
      databaseName: RFN200
      driverType: '4'
      jndiName: jdbc/BPE_232
      name: BPE_232
      portNumber: '50004'
      serverName: s298lr2dbrf02.ref.cpc998.be
      typeds: universal
      user: dborc232
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: refiorc297/dborc235
      authDataPassword: 235aiouz
      currentSchema: ORC235
      enableSeamlessFailover: 0
      databaseName: RFN200
      driverType: '4'
      jndiName: jdbc/BPE_235
      name: BPE_235
      portNumber: '50004'
      serverName: s298lr2dbrf02.ref.cpc998.be
      typeds: universal
      user: dborc235
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: REF/JRDE203
      authDataPassword: mqsrk203
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      extendedDynamic: 'false'
      jndiName: jdbc/JADE2_203
      libraries: '*LIBL'
      name: JADE2_203
      naming: system
      package: DSJ2203
      packageCriteria: select
      packageLibrary: JADEBUS203
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE203
      connectionPool:
         connectionTimeout: 30
         maxConnections: 50
         minConnections: 15
         reapTime: 300
         agedTimeout: 0 

    - authDataAlias: REF/JRDE216
      authDataPassword: aoeij216
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      extendedDynamic: 'false'
      jndiName: jdbc/JADE2_216
      libraries: '*LIBL'
      name: JADE2_216
      naming: system
      package: DSJ2216
      packageCriteria: select
      packageLibrary: JADEBUS216
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE216
      connectionPool:
         connectionTimeout: 30
         maxConnections: 50
         minConnections: 15
         reapTime: 300
         agedTimeout: 0 

    - authDataAlias: REF/JRDE232
      authDataPassword: mqdke232
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      extendedDynamic: 'false'
      jndiName: jdbc/JADE2_232
      libraries: '*LIBL'
      name: JADE2_232
      naming: system
      package: DSJ2232
      packageCriteria: select
      packageLibrary: JADEBUS232
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE232
      connectionPool:
         connectionTimeout: 30
         maxConnections: 50
         minConnections: 15
         reapTime: 300
         agedTimeout: 0 

    - authDataAlias: REF/JRDE235
      authDataPassword: seiod235
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      extendedDynamic: 'false'
      jndiName: jdbc/JADE2_235
      libraries: '*LIBL'
      name: JADE2_235
      naming: system
      package: DSJ2235
      packageCriteria: select
      packageLibrary: JADEBUS235
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE235
      connectionPool:
         connectionTimeout: 30
         maxConnections: 50
         minConnections: 15
         reapTime: 300
         agedTimeout: 0 

    directories:
    - '{{ path }}/work/jobs'

  roles:
  - base_was
