---
- hosts: ProdNode_AIRBUS_200B_FLUX
  user: root
  vars:
    was_app_name: EFACT_200_MBR2
    was_cluster_name: EFACT_200
    default_port: 21160
    owner: was6u200
    group: was6group
    path: /data/efact/{{ was_app_name }}

    vhost: EFACT_200_vhost
    host_aliases:
    - hostname: efac2xx.jablux.cpc998.be
      port: 443
    - hostname: s298lp{{ dc }}wsrp01.jablux.cpc998.be
      port: 443
    - hostname: s298lp{{ dc }}wsrp02.jablux.cpc998.be
      port: 443
    - hostname: s298lp{{ dc }}wsfl01.jablux.cpc998.be
      port: 21160
    - hostname: s298lp{{ dc }}wsfl02.jablux.cpc998.be
      port: 21160
    - hostname: s298lp{{ dc }}wsfl01.jablux.cpc998.be
      port: 21161
    - hostname: s298lp{{ dc }}wsfl02.jablux.cpc998.be
      port: 21161

    dataSources:
    - authDataAlias: AIRBUS/JCARE200
      authDataPassword: AKELD52
      dataTruncation: 'false'
      databaseName: AIRBUS
      dateFormat: iso
      jndiName: jdbc/EFAC_AS400_RC
      libraries: '*LIBL'
      name: AS400EFACT_200
      naming: system
      serverName: airbus.jablux.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JCARE200

    - authDataAlias: AIRBUS/JCARE200
      authDataPassword: AKELD52
      dataTruncation: 'false'
      databaseName: EFACT
      dateFormat: iso
      jndiName: jdbc/EFAC_AS400_RO_RC
      libraries: '*LIBL'
      name: AS400_RO_EFACT_200
      naming: system
      serverName: efact.mutworld.be
      timeFormat: iso
      typeds: toolbox
      user: JCARE200
      connectionPool:
         maxConnections: 50
         minConnections: 5

    - authDataAlias: udbidmg2/dbmct200
      authDataPassword: 19jun091541
      clientRerouteAlternatePortNumber: 50008
      clientRerouteAlternateServerName: "{{ standby }}"
      currentSchema: CARE
      enableSeamlessFailover: 1
      databaseName: MCT200
      driverType: 4
      jndiName: jdbc/EFAC_LINUX_RC
      name: LNXEFACT_200
      portNumber: 50008
      serverName: "{{ primary }}"
      typeds: universal
      user: dbmct200
      webSphereDefaultIsolationLevel: 2
      connectionPool:
        maxConnections: 50
        minConnections: 5

    jmscf:
    - jndiName: jms/mqIIBConnectionFactory 
      qmgrName: PQM2FL1
      qmgrSvrconnChannel: MTEAM.CLIENT.SVRCONN
      connectionNameList: s298lp1iib01.jablux.cpc998.be(16200),s298lp1iib02.jablux.cpc998.be(16200)
      authDataAlias: JMSCF/uqmfl200
      user: uqmfl200
      authDataPassword: Welcome01
      name: EFACT_mqConnectionFactory

    - jndiName: jms/mqConnectionFactory
      qmgrName: QM.200
      qmgrSvrconnChannel: SYSTEM.DEF.SVRCONN
      connectionNameList: airbus.jablux.cpc998.be(14200)
      authDataAlias: AIRBUS/JCARE200
      user: JCARE200
      authDataPassword: AKELD52
      name: EFACT_JMS_Connection_Factory

    - jndiName: jms/mqConnectionFactory_ro
      qmgrName: QM.200
      qmgrSvrconnChannel: SYSTEM.DEF.SVRCONN
      connectionNameList: efact.mutworld.be(14200)
      authDataAlias: AIRBUS/JCARE200
      user: JCARE200
      authDataPassword: AKELD52
      name: EFACT_JMS_Connection_Factory_RO

    jmsq:
    - jndiName: jms/EFAC_IN
      queueName: QA.EFAC_IN
      advancedProperties:
        useRFH2: 'false'

    - jndiName: jms/EFAC_OUT
      queueName: QA.EFAC_OUT

    - jndiName: jms/QA.NIPPIN.ASYNC.GENERIC.OUT
      queueName: QA.NIPPIN.ASYNC.GENERIC.OUT
      advancedProperties:
        useRFH2: 'false'

    - jndiName: jms/QA.NIPPIN.LOGS
      queueName: QA.INAMI.MODEL.LOGS
      advancedProperties:
        useRFH2: 'false'

    - jndiName: jms/QA.INAMI.MODEL.ENCRYPT.REQ
      queueName: QA.INAMI.MODEL.ENCRYPT.REQ
      advancedProperties:
        useRFH2: 'false'

    - jndiName: jms/QA.INAMI.MODEL.ENCRYPT.RESP
      queueName: QA.INAMI.MODEL.ENCRYPT.RESP
      advancedProperties:
        useRFH2: 'false'

    resourceEnvEntries:
    - name: EFACTConfig
      jndiName: config/efacConfig
      customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/efact.properties"
    - name: EfactSoapParser
      jndiName: config/soapParserConfig
      customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/soapParser.properties"

    systemProperties:
    - name: spring.profiles.active
      value: was

    resourceFiles:
    - files/EFACT/efact.properties
    - files/EFACT/soapParser.properties
    - files/EFACT/aesSymetric2013prod.key

  roles:
  - base_was

  tasks:
  - name: add security.provider.12 properties
    lineinfile: dest=/opt/WebSphere85/AppServer/java_1.7_64/jre/lib/security/java.security
      regexp="^security\.provider\.12.*$"
      line="security.provider.12=org.bouncycastle.jce.provider.BouncyCastleProvider"
      insertafter="security.provider.11.*"
      backup=yes
    tags: files

  - name: copy bcprov-jdk16-1.45.jar
    copy: src=files/EFACT/bcprov-jdk16-1.45.jar
      dest=/opt/WebSphere85/AppServer/java_1.7_64/jre/lib/ext/bcprov-jdk16-1.45.jar
      backup=yes
    tags: files

  - name: copy local_policy.jar and US_export_policy.jar
    copy: src=files/EFACT/{{ item }}
      dest=/opt/WebSphere85/AppServer/java_1.7_64/jre/lib/security/{{ item }}
      backup=yes
    with_items:
    - local_policy.jar
    - US_export_policy.jar
    tags: files

  - name: check if resources/soapParserSEQUENCE.txt exists for EFAC
    stat: path={{ path }}/resources/soapParserSEQUENCE.txt
    register: st
    tags: files

  - name: create resources/soapParserSEQUENCE.txt if does not exist
    when: not st.stat.exists
    lineinfile: dest="{{ path }}/resources/soapParserSEQUENCE.txt" create=yes group={{ group }} mode=0644 owner={{ owner }} line="0"
    tags: files
