---
- hosts: ProdNode_AIRBUS_200A_FLUX
  user: root
  vars:
    was_app_name: MYCARENET_200_MBR1
    was_cluster_name: MYCARENET_200
    default_port: 21200
    owner: was6u200
    group: was6group
    path: /data/mycarenet/{{ was_app_name }}

    vhost: MYCARENET_200_vhost
    host_aliases:
    - hostname: mycarenetxml2xx.jablux.cpc998.be
      port: 443
    - hostname: s298lp{{ dc }}wsrp01.jablux.cpc998.be
      port: 443
    - hostname: s298lp{{ dc }}wsrp02.jablux.cpc998.be
      port: 443
    - hostname: s298lp{{ dc }}wsfl01.jablux.cpc998.be
      port: 21200
    - hostname: s298lp{{ dc }}wsfl02.jablux.cpc998.be
      port: 21200
    - hostname: s298lp{{ dc }}wsfl01.jablux.cpc998.be
      port: 21201
    - hostname: s298lp{{ dc }}wsfl02.jablux.cpc998.be
      port: 21201

    dataSources:
    - authDataAlias: AIRBUS/JCARE200
      authDataPassword: AKELD52
      dataTruncation: 'false'
      databaseName: AIRBUS
      dateFormat: iso
      jndiName: jdbc/CARENET_AS400_RC
      libraries: '*LIBL'
      name: AS400MCT_200
      naming: system
      serverName: airbus.jablux.cpc998.be
      timeFormat: iso
      typeds: toolbox
      user: JCARE200
      connectionPool:
         maxConnections: 50
         minConnections: 5

    - authDataAlias: udbidmg2/dbmct200
      authDataPassword: 3006beatit
      clientRerouteAlternatePortNumber: 50008
      clientRerouteAlternateServerName: "{{ standby }}"
      currentSchema: CARE
      enableSeamlessFailover: 1
      databaseName: MCT200
      driverType: 4
      jndiName: jdbc/CARENET_LINUX_RC
      name: LNXMCT_200
      portNumber: 50008
      serverName: "{{ primary }}"
      typeds: universal
      user: dbmct200
      webSphereDefaultIsolationLevel: 2
      connectionPool:
        maxConnections: 100
        minConnections: 5

# not used for the moment, but keep for later
#    jmscf:
#    - jndiName: jms/mqConnectionFactory 
#      qmgrName: QM.FL.200
#      qmgrSvrconnChannel: MTEAM.ADMIN.SVRCONN
#      connectionNameList: s998jrlnx080.ref.cpc998.be(15500),s998jrlnx081.ref.cpc998.be(15500)
#      authDataAlias: JMSCF/uqmfl200
#      user: uqmfl200
#      authDataPassword: Welcome01
#      name: MYCARENET_mqConnectionFactory

#    jmsq:
#    - jndiName: jms/MYCARENET_EXTENTED_IN
#      queueName: QA.MYCARENET.EXTENDED.IN

    resourceEnvEntries:
    - name: CarenetConfig
      jndiName: config/CarenetConfig
      customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/carenet.properties"

    systemProperties:
    - name: spring.profiles.active
      value: was
    - name: file.encoding
      value: ISO-8859-15
    - name: mule.encoding
      value: ISO-8859-15

    resourceFiles:
    - files/MYCARENET/carenet.properties

  roles:
  - base_was
