---
- hosts: jvirtRefDpz80
  user: root
  vars:
    was_app_name: DPZ_20080
    default_port: 21080
    owner: was8dpz
    group: was6group
    path: /data/dpz/{{ was_app_name }}

  roles:
  - base_was
