---
- hosts: IntegNode_500A_FLUX
  user: root
  vars:
    was_app_name: DMG_500_MBR1
    was_cluster_name: DMG_500
    default_port: 21080
    owner: was6u500
    group: was6group
    path: /data/dmg/{{ was_app_name }}

    vhost: DMG_500_vhost
    host_aliases:
    - hostname: dmg-integ.integ.gfdi.be
      port: 443
    - hostname: s998li2wsrp01.integ.gfdi.be
      port: 443
    - hostname: s598li2wsfl01.integ.gfdi.be
      port: 21080
    - hostname: s598li2wsfl01.integ.gfdi.be
      port: 21081

    dataSources:
    - authDataAlias: AS400/JCARE500
      authDataPassword: MAQID31
      dataTruncation: 'false'
      databaseName: INTEGGFDI
      dateFormat: iso
      jndiName: jdbc/DMG_AS400_RC
      libraries: '*LIBL'
      name: AS400DMG_500
      naming: system
      serverName: integ.integ.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JCARE500

    - authDataAlias: lnxdb2/dbmct500
      authDataPassword: 19jun091541
      clientRerouteAlternatePortNumber: 50004
      clientRerouteAlternateServerName: s000li2dbfl01.integ.gfdi.be
      currentSchema: CARE
      enableSeamlessFailover: 1
      databaseName: MCT500
      driverType: 4
      jndiName: jdbc/DMG_LINUX_RC
      name: LNXGDMG_500
      portNumber: 50004
      serverName: s000li2dbfl01.integ.gfdi.be
      typeds: universal
      user: dbmct500
      webSphereDefaultIsolationLevel: 2
      statementCacheSize: 500
      connectionPool:
        maxConnections: 50
        minConnections: 5

    jmscf:
    - jndiName: jms/mqIIBConnectionFactory 
      qmgrName: NQM5FL1
      qmgrSvrconnChannel: MTEAM.CLIENT.SVRCONN
      connectionNameList: s598li2iib03.integ.gfdi.be(16500)
      authDataAlias: JMSCF/uqmfl500
      user: uqmfl500
      authDataPassword: Welcome01
      name: DMG_mqConnectionFactory
      connectionPool:
        minConnections: 1
        maxConnections: 20

    jmsq:
    - jndiName: jms/DMG_CONSULT_IN
      queueName: QA.DMG.CONSULT.IN
      advancedProperties:
        useRFH2: 'false'
    - jndiName: jms/DMG_CONSULT_OUT
      queueName: QA.DMG.CONSULT.OUT
    - jndiName: jms/DMG_CONSULT_LIST_IN
      queueName: QA.DMG.CONSULT.LIST.IN
      advancedProperties:
        useRFH2: 'false'
    - jndiName: jms/DMG_CONSULT_LIST_OUT
      queueName: QA.DMG.CONSULT.LIST.OUT
    - jndiName: jms/DMG_NOTIFY_IN
      queueName: QA.DMG.NOTIFY.IN
      advancedProperties:
        useRFH2: 'false'
    - jndiName: jms/DMG_NOTIFY_OUT
      queueName: QA.DMG.NOTIFY.OUT
    - jndiName: jms/DMG_CLOSURE_OUT
      queueName: QA.DMG.CLOSURE.OUT
    - jndiName: jms/DMG_PROLONG_OUT
      queueName: QA.DMG.PROLONG.OUT
    - jndiName: jms/DMG_SUBSCRIPTION_IN
      queueName: QA.DMG.SUBSCRIPTION.IN
      advancedProperties:
        useRFH2: 'false'
    - jndiName: jms/DMG_SUBSCRIPTION_OUT
      queueName: QA.DMG.SUBSCRIPTION.OUT

    resourceEnvEntries:
    - name: DMGConfig
      jndiName: config/dmgConfig
      customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/dmg.properties"

    systemProperties:
    - name: spring.profiles.active
      value: was

    resourceFiles:
    - files/DMG/dmg.properties

  roles:
  - base_was
