---
- hosts: IntegNode_500A_FLUX
  user: root
  vars:
    was_app_name: NIPCOMT_500_MBR1
    was_cluster_name: NIPCOMT_500
    default_port: 21320
    owner: was6u500
    group: was6group
    path: /data/nipcomt/{{ was_app_name }}

    dataSources: False

    vhost: NCT_500_vhost
    host_aliases:
    - hostname: nct-integ.integ.gfdi.be
      port: 443
    - hostname: s998li2wsrp01.integ.gfdi.be
      port: 443
    - hostname: s598li2wsfl01.integ.gfdi.be
      port: 21320
    - hostname: s598li2wsfl01.integ.gfdi.be
      port: 21321

    jmscf:
    - jndiName: jms/mqIIBConnectionFactory 
      qmgrName: NQM5FL1
      qmgrSvrconnChannel: MTEAM.CLIENT.SVRCONN
      connectionNameList: s598li2iib03.integ.gfdi.be(16500)
      authDataAlias: JMSCF/uqmfl500
      user: uqmfl500
      authDataPassword: Welcome01
      name: NCT_mqConnectionFactory

    jmsq:
    - jndiName: jms/QA.INAMI.MODEL.BIM_BATCH.REQ
      queueName: QA.INAMI.MODEL.BIM_BATCH.REQ
      advancedProperties:
        useRFH2: 'false'

    - jndiName: jms/QA.NIPPIN.ASYNC.GENERIC.OUT
      queueName: QA.NIPPIN.ASYNC.GENERIC.OUT

    - jndiName: jms/QA.NIPPIN.ASYNC.GENERIC.OUT.BIG
      queueName: QA.NIPPIN.ASYNC.GENERIC.OUT.BIG

    - jndiName: jms/QA.NIPPIN.ASYNC.GENERIC.REQ
      queueName: QA.NIPPIN.ASYNC.GENERIC.REQ

    - jndiName: jms/QA.NIPPIN.ASYNC.GENERIC.RESP
      queueName: QA.NIPPIN.ASYNC.GENERIC.RESP

    - jndiName: jms/QA.NIPPIN.ASYNC.NCT.DB.IN
      queueName: QA.NIPPIN.ASYNC.NCT.DB.IN

    - jndiName: jms/QA.NIPPIN.ASYNC.NCT.DB.OUT
      queueName: QA.NIPPIN.ASYNC.NCT.DB.OUT

    dataSources:
    - authDataAlias: lnxdb2/dbmct500
      authDataPassword: 19jun091541
      clientRerouteAlternatePortNumber: 50004
      clientRerouteAlternateServerName: s000li2dbfl01.integ.gfdi.be
      currentSchema: CARE
      databaseName: MCT500
      enableSeamlessFailover: 1
      driverType: 4
      jndiName: jdbc/NCT_LINUX_RC
      name: LNXNCT_500
      portNumber: 50004
      serverName: s000li2dbfl01.integ.gfdi.be
      typeds: universal
      user: dbmct500
      webSphereDefaultIsolationLevel: 2
      connectionPool:
        maxConnections: 50
        minConnections: 5

    resourceEnvEntries:
    - name: NippinCommonToolsForJNDI
      jndiName: config/NippinCommonToolsConfig
      customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/NippinCommonToolsConfig.properties"

    resourceFiles:
    - files/NCT/aesSymetric2013prod.key
    - files/NCT/NippinCommonToolsConfig.properties
    - files/NCT/Assu_Async.csv
    - files/NCT/eAttest_CrossChecks.csv
    - files/NCT/eAttest_Rules.csv
    - files/NCT/eAttest_XPath.csv
    - files/NCT/eFact_Rules.csv
    - files/NCT/managedFlowsFile.properties

  roles:
  - base_was
