---
- hosts: IntegNode_500A_FLUX
  user: root
  vars:
    was_app_name: SAMDB_500_MBR1
    was_cluster_name: SAMDB_500
    default_port: 21240
    owner: was6u500
    group: was6group
    path: /data/samdb/{{ was_app_name }}

    vhost: SAMDB_500_vhost
    host_aliases:
    - hostname: samdb-integ.integ.gfdi.be
      port: 80
    - hostname: s998li2wsrp01.integ.gfdi.be
      port: 80
    - hostname: s598li2wsfl01.integ.gfdi.be
      port: 21240
    - hostname: s598li2wsfl01.integ.gfdi.be
      port: 21241

    dataSources:
    - authDataAlias: AS400/JCARE500
      authDataPassword: MAQID31
      dataTruncation: 'false'
      databaseName: INTEGGFDI
      dateFormat: iso
      jndiName: jdbc/DBSAM_AS400_RC
      libraries: '*LIBL'
      name: AS400DBSAM_500
      naming: system
      serverName: integ.integ.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JCARE500

    resourceEnvEntries:
    - name: SamdbRessourceConfig
      jndiName: config/dbsamConfig
      customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/ch4_dbsam.properties"

    resourceFiles:
    - files/SAMDB/ch4_dbsam.properties

  roles:
  - base_was
