---
- hosts: jabluxProdNodeapps502
  user: root
  vars:
    was_app_name: DMG_apps5_MBR2
    was_cluster_name: DMG_apps5
    default_port: 22060
    group: was6group
    owner: was6u500
    path: /data/dmg/{{ was_app_name }}

    host_aliases:
    - hostname: dmg5xx.jablux.cpc998.be
      port: '443'
    - hostname: dmg5xx.jablux.cpc998.be
      port: '80'

    resourceEnvEntries:
    - customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/dmg.properties"
      jndiName: config/dmgConfig
      name: DMGConfig

    resourceFiles:
    - files/DMG/dmg.properties

    systemProperties:
    - name: spring.profiles.active
      value: was

  roles:
  - base_was
