---
- hosts: jabluxProdNodeapps501
  user: root
  vars:
    was_app_name: MYCARENET_apps5_MBR1
    was_cluster_name: MYCARENET_apps5
    default_port: 21120
    group: was6group
    owner: was6u500
    path: /data/mycarenet/{{ was_app_name }}

    resourceEnvEntries:
    - customprop:
      - name: path
        type: java.lang.String
        value: "{{ path }}/resources/carenet.properties"
      jndiName: config/CarenetConfig
      name: CarenetConfig

    resourceFiles:
    - files/MYCARENET/carenet.properties

    systemProperties:
    - name: spring.profiles.active
      value: was

  roles:
  - base_was
