---
- hosts: PreProdNode_BETA_500A_RFND
  user: root
  vars:
    was_app_name: JADER_BETA_MBR1
    was_cluster_name: JADER_BETA
    owner: was6bet
    group: was6group
    default_port: 21080
    path: /data/jade/{{ was_app_name }}

    vhost: RfndBeta_vhost
    host_aliases:
    - hostname: s999lq2wsrf05.jablux.gfdi.be
      port: 21080

    systemProperties:
    - name: jade2.jobs.500
      value: true
    - name: jade2.jobs.501
      value: true
    - name: jade2.jobs.509
      value: true
    - name: jade2.jobs.JADE2_SERVER
      value: true
    - name: net.sf.ehcache.skipUpdateCheck
      value: true
  
    dataSources:
    - authDataAlias: BETA/JRDE500
      authDataPassword: P2DE500
      dataTruncation: 'false'
      databaseName: GFDIDB2
      dateFormat: iso
      jndiName: jdbc/JADE2_500
      libraries: '*LIBL'
      name: JADE2_500
      naming: system
      serverName: s444b58a.jablux.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE500
      extendedDynamic: false
      package: DSJ2500
      packageLibrary: JADEBUS500
      packageCriteria: select

    - authDataAlias: BETA/JRDE501
      authDataPassword: P2DE501
      dataTruncation: 'false'
      databaseName: GFDIDB2
      dateFormat: iso
      jndiName: jdbc/JADE2_501
      libraries: '*LIBL'
      name: JADE2_501
      naming: system
      serverName: s444b58a.jablux.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE501
      extendedDynamic: false
      package: DSJ2501
      packageLibrary: JADEBUS501
      packageCriteria: select

    - authDataAlias: BETA/JRDE509
      authDataPassword: P2DE509
      dataTruncation: 'false'
      databaseName: GFDIDB2
      dateFormat: iso
      jndiName: jdbc/JADE2_509
      libraries: '*LIBL'
      name: JADE2_509
      naming: system
      serverName: s444b58a.jablux.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE509
      extendedDynamic: false
      package: DSJ2509
      packageLibrary: JADEBUS509
      packageCriteria: select

    - authDataAlias: BETA/JRDE988
      authDataPassword: P2DE988
      dataTruncation: 'false'
      databaseName: GFDIDB2
      dateFormat: iso
      jndiName: jdbc/JADE2_999
      libraries: '*LIBL'
      name: JADE2_999
      naming: system
      serverName: s444b58a.jablux.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE988
      extendedDynamic: false
      package: DSJ2999
      packageLibrary: JADEBUS999
      packageCriteria: select

    - authDataAlias: udbibet97/dborcbet
      authDataPassword: bet20090204
      currentSchema: ORC500
      databaseName: RFN500
      driverType: '4'
      jndiName: jdbc/BPE_500
      name: BPE_500
      portNumber: '50004'
      serverName: s999lq2dbrf03.jablux.gfdi.be
      typeds: universal
      user: dborcbet
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: udbibet97/dborcbet
      authDataPassword: bet20090204
      currentSchema: ORC501
      databaseName: RFN500
      driverType: '4'
      jndiName: jdbc/BPE_501
      name: BPE_501
      portNumber: '50004'
      serverName: s999lq2dbrf03.jablux.gfdi.be
      typeds: universal
      user: dborcbet
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: udbibet97/dborcbet
      authDataPassword: bet20090204
      currentSchema: ORC509
      databaseName: RFN500
      driverType: '4'
      jndiName: jdbc/BPE_509
      name: BPE_509
      portNumber: '50004'
      serverName: s999lq2dbrf03.jablux.gfdi.be
      typeds: universal
      user: dborcbet
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: udbibet97/dborcbet
      authDataPassword: bet20090204
      currentSchema: ORC999
      databaseName: RFN500
      driverType: '4'
      jndiName: jdbc/BPE_999
      name: BPE_999
      portNumber: '50004'
      serverName: s999lq2dbrf03.jablux.gfdi.be
      typeds: universal
      user: dborcbet
      webSphereDefaultIsolationLevel: '2'

    directories:
    - '{{ path }}/work/jobs'

  roles:
  - base_was

