---
- hosts: IntegNode_500C_RFND
  user: root
  vars:
    was_app_name: CATA_500_MBR1
    was_cluster_name: CATA_500
    owner: was6u500
    group: was6group
    default_port: 21040
    path: /data/cata/{{ was_app_name }}

    vhost: RfndInteg_vhost
    host_aliases:
    - hostname: "{{ ansible_fqdn }}" 
      port: "{{ default_port }}"

    dataSources:
    - authDataAlias: lnxdb2/dbcat500
      authDataPassword: ertgf23
      currentSchema: ADM
      enableSeamlessFailover: 0
      databaseName: CAT500
      driverType: '4'
      jndiName: jdbc/DCADM5XX
      name: DCADM5XX
      portNumber: '50004'
      serverName: s598li2dbrf01.integ.gfdi.be
      typeds: universal
      user: dbcat500
      webSphereDefaultIsolationLevel: '1'
      connectionPool:
        maxConnections: 80
        minConnections: 20

    - authDataAlias: lnxdb2/dbcat500
      authDataPassword: ertgf23
      currentSchema: IDX
      enableSeamlessFailover: 0
      databaseName: CAT500
      driverType: '4'
      jndiName: jdbc/DCIDX5XX
      name: DCIDX5XX
      portNumber: '50004'
      serverName: s598li2dbrf01.integ.gfdi.be
      typeds: universal
      user: dbcat500
      webSphereDefaultIsolationLevel: '1'
      connectionPool:
        maxConnections: 80
        minConnections: 20


    systemProperties:
    - name: doccenter.scheduler.enabled
      value: true
    - name: doccenter.scheduler.threads
      value: '1'
    - name: doccenter.script.folderref.recheck.delay
      value: '-1'
    - name: net.sf.ehcache.skipUpdateCheck
      value: true

    directories:
    - "{{ path }}/work/logs"
    - /data/cata/integ
    - /data/cata/integ/500
    - /data/cata/integ/500/chunks
    - /data/cata/integ/500/config
    - /data/cata/integ/500/config/dbspecific
    - /data/cata/integ/500/config/dbspecific/DCIDX5XX
    - /data/cata/integ/500/dccache
    - /data/cata/integ/500/logs
    - /data/cata/integ/500/work

  roles:
  - base_was

  # Post Install
  tasks:
  - name: Copy dbspecific.zip
    copy: src="files/CATA/dbspecific.zip" dest="/data/cata/integ/500/config/dbspecific.zip"
      owner={{ owner }} group={{ group }} mode=0644
    register: dbspecific_zip
    tags: files
    notify: reset_acl

  - name: Extract dbspecific.zip if uploaded
    when: dbspecific_zip.changed
    unarchive: src="/data/cata/integ/500/config/dbspecific.zip"
      dest="/data/cata/integ/500/config/dbspecific/DCIDX5XX/"
      owner={{ owner }} group={{ group }} mode=u=rwX,g=rX,o=rX copy=no
    tags: files
    notify: reset_acl

  - name: Copy dbdefault.zip
    copy: src="files/CATA/dbdefault.zip" dest="/data/cata/integ/500/config/dbdefault.zip"
      owner={{ owner }} group={{ group }} mode=0644
    register: dbdefault_zip
    tags: files
    notify: reset_acl

  - name: Extract dbdefault.zip if uploaded
    when: dbdefault_zip.changed
    unarchive: src="/data/cata/integ/500/config/dbdefault.zip"
      dest="/data/cata/integ/500/config/"
      owner={{ owner }} group={{ group }} mode=u=rwX,g=rX,o=rX copy=no creates="/data/cata/integ/500/config/dbdefault"
    tags: files
    notify: reset_acl

  