---
- hosts: IntegNode_200C_RFND
  user: root
  vars:
    was_app_name: CATA_200_MBR1
    was_cluster_name: CATA_200
    default_port: 21040
    path: /data/cata/{{ was_app_name }}
    owner: was6u200
    group: was6group

    vhost: RfndInteg_vhost
    host_aliases:
    - hostname: "{{ ansible_fqdn }}" 
      port: "{{ default_port }}"
    
    dataSources:
    - authDataAlias: lnxdb2/dbcat200
      authDataPassword: 200opioj
      currentSchema: ADM
      enableSeamlessFailover: 0
      databaseName: CAT200
      driverType: '4'
      jndiName: jdbc/DCADM2XX
      name: DCADM2XX
      portNumber: '50004'
      serverName: s298li2dbrf01.integ.gfdi.be
      typeds: universal
      user: dbcat200
      webSphereDefaultIsolationLevel: '1'

    - authDataAlias: lnxdb2/dbcat200
      authDataPassword: 200opioj
      currentSchema: IDX
      enableSeamlessFailover: 0
      databaseName: CAT200
      driverType: '4'
      jndiName: jdbc/DCIDX2XX
      name: DCIDX2XX
      portNumber: '50004'
      serverName: s298li2dbrf01.integ.gfdi.be
      typeds: universal
      user: dbcat200
      webSphereDefaultIsolationLevel: '1'

    systemProperties:
    - name: doccenter.scheduler.enabled
      value: true
    - name: doccenter.scheduler.threads
      value: '1'
    - name: doccenter.script.folderref.recheck.delay
      value: '-1'
    - name: net.sf.ehcache.skipUpdateCheck
      value: true

    directories:
    - "{{ path }}/work/logs"
    - /data/cata/integ
    - /data/cata/integ/200
    - /data/cata/integ/200/chunks
    - /data/cata/integ/200/config
    - /data/cata/integ/200/config/dbspecific
    - /data/cata/integ/200/config/dbspecific/DCIDX2XX
    - /data/cata/integ/200/dccache
    - /data/cata/integ/200/logs
    - /data/cata/integ/200/work

  roles:
  - base_was

  # Post Install
  tasks:
  - name: Copy dbspecific.zip
    copy: src="files/CATA/dbspecific.zip" dest="/data/cata/integ/200/config/dbspecific.zip"
      owner={{ owner }} group={{ group }} mode=0644
    register: dbspecific_zip
    tags: files
    notify: reset_acl

  - name: Extract dbspecific.zip if uploaded
    when: dbspecific_zip.changed
    unarchive: src="/data/cata/integ/200/config/dbspecific.zip"
      dest="/data/cata/integ/200/config/dbspecific/DCIDX2XX/"
      owner={{ owner }} group={{ group }} mode=u=rwX,g=rX,o=rX copy=no
    tags: files
    notify: reset_acl

  - name: Copy dbdefault.zip
    copy: src="files/CATA/dbdefault.zip" dest="/data/cata/integ/200/config/dbdefault.zip"
      owner={{ owner }} group={{ group }} mode=0644
    register: dbdefault_zip
    tags: files
    notify: reset_acl

  - name: Extract dbdefault.zip if uploaded
    when: dbdefault_zip.changed
    unarchive: src="/data/cata/integ/200/config/dbdefault.zip"
      dest="/data/cata/integ/200/config/"
      owner={{ owner }} group={{ group }} mode=u=rwX,g=rX,o=rX copy=no creates="/data/cata/integ/200/config/dbdefault"
    tags: files
    notify: reset_acl

  