---
- hosts: IntegNode_500A_RFND
  user: root
  vars:
    was_app_name: INTG_500
    default_port: 21160
    path: /data/intg/{{ was_app_name }}
    group: was6group
    owner: was6u500

    vhost: RfndInteg_vhost
    host_aliases:
    - hostname: "{{ ansible_fqdn }}" 
      port: "{{ default_port }}"

    systemProperties:
    - name: intg.jndi.prefix
      value: jndi
    - name: net.sf.ehcache.skipUpdateCheck
      value: true

    dataSources:
    - authDataAlias: lnxdb2/dbint500
      authDataPassword: 500fkghu
      currentSchema: INTG
      enableSeamlessFailover: 0
      databaseName: RFN500
      driverType: '4'
      jndiName: jdbc/INTG_500
      name: INTG_500
      portNumber: '50004'
      serverName: s598li2dbrf02.integ.gfdi.be
      typeds: universal
      user: dbint500
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: AS400/INTG500
      authDataPassword: ms500eop
      dataTruncation: 'false'
      databaseName: INTEGGFDI
      dateFormat: iso
      extendedDynamic: 'false'
      jndiName: jdbc/JADE2_500
      libraries: '*LIBL'
      name: JADE2_500
      naming: system
      package: DSJ2500
      packageCriteria: select
      packageLibrary: JADEBUS500
      serverName: integ.integ.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: INTG500

  roles:
  - base_was