---
- hosts: PreProdNode_FROZENGFDI_500fA_RFND
  user: root
  vars:
    was_app_name: CATA_500f_MBR1
    was_cluster_name: CATA_500f
    owner: was6u500
    group: was6group
    default_port: 21120
    path: /data/cata/{{ was_app_name }}

    vhost: RfndFrozen_vhost

    dataSources:
    - authDataAlias: udbifrozen97/dbcat500
      authDataPassword: ertgf23
      currentSchema: ADM
      databaseName: CAT500
      driverType: '4'
      jndiName: jdbc/DCADM5XX
      name: DCADM5XX
      portNumber: '50004'
      serverName: s509lq2dbrf01.jablux.gfdi.be
      typeds: universal
      user: dbcat500
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: udbifrozen97/dbcat500
      authDataPassword: ertgf23
      currentSchema: IDX
      databaseName: CAT500
      driverType: '4'
      jndiName: jdbc/DCIDX5XX
      name: DCIDX5XX
      portNumber: '50004'
      serverName: s509lq2dbrf01.jablux.gfdi.be
      typeds: universal
      user: dbcat500
      webSphereDefaultIsolationLevel: '1'


    systemProperties:
    - name: doccenter.scheduler.enabled
      value: false
    - name: doccenter.scheduler.threads
      value: '0'
    - name: doccenter.script.folderref.recheck.delay
      value: '-1'
    - name: net.sf.ehcache.skipUpdateCheck
      value: true

  roles:
  - base_was

