---
- hosts: PreProdNode_FROZENGFDI_500fA_RFND
  user: root
  vars:
    was_app_name: JADER_500f_MBR1
    was_cluster_name: JADER_500f
    owner: was6u500
    group: was6group
    default_port: 21080
    path: /data/jade/{{ was_app_name }}

    vhost: RfndFrozen_vhost

    dataSources:
    - authDataAlias: FROZEN/JRDE500
      authDataPassword: fcnie500
      dataTruncation: 'false'
      databaseName: FROZENGFDI
      dateFormat: iso
      jndiName: jdbc/JADE2_500
      libraries: '*LIBL'
      name: JADE2_500
      naming: system
      serverName: frozen.jablux.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE500
      extendedDynamic: false
      package: DSJ2500
      packageLibrary: JADEBUS500
      packageCriteria: select

    - authDataAlias: FROZEN/JRDE509
      authDataPassword: ojizu509
      dataTruncation: 'false'
      databaseName: FROZENGFDI
      dateFormat: iso
      jndiName: jdbc/JADE2_509
      libraries: '*LIBL'
      name: JADE2_509
      naming: system
      serverName: frozen.jablux.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE509
      extendedDynamic: false
      package: DSJ2509
      packageLibrary: JADEBUS509
      packageCriteria: select

    - authDataAlias: FROZEN/JRDE527
      authDataPassword: erior527
      dataTruncation: 'false'
      databaseName: FROZENGFDI
      dateFormat: iso
      jndiName: jdbc/JADE2_527
      libraries: '*LIBL'
      name: JADE2_527
      naming: system
      serverName: frozen.jablux.gfdi.be
      timeFormat: iso
      typeds: toolbox
      user: JRDE527
      extendedDynamic: false
      package: DSJ2527
      packageLibrary: JADEBUS527
      packageCriteria: select

    - authDataAlias: udbifrozen97/dborc500
      authDataPassword: 500lkjds
      currentSchema: ORC500
      databaseName: ORC500
      driverType: '4'
      jndiName: jdbc/BPE_500
      name: BPE_500
      portNumber: '50004'
      serverName: s509lq2dbrf02.jablux.gfdi.be
      typeds: universal
      user: dborc500
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: udbifrozen97/dborc509
      authDataPassword: 509mlksq
      currentSchema: ORC509
      databaseName: ORC500
      driverType: '4'
      jndiName: jdbc/BPE_509
      name: BPE_509
      portNumber: '50004'
      serverName: s509lq2dbrf02.jablux.gfdi.be
      typeds: universal
      user: dborc509
      webSphereDefaultIsolationLevel: '2'

    - authDataAlias: udbifrozen97/dborc527
      authDataPassword: 527qlmkd
      currentSchema: ORC527
      databaseName: ORC500
      driverType: '4'
      jndiName: jdbc/BPE_527
      name: BPE_527
      portNumber: '50004'
      serverName: s509lq2dbrf02.jablux.gfdi.be
      typeds: universal
      user: dborc527
      webSphereDefaultIsolationLevel: '2'

  roles:
  - base_was

