---
- hosts:  IntegNode_500A_EB
  user: root
  vars:
    was_app_name: BCMPCH_500a_MBR1
    was_cluster_name:  BCMPCH_500a
    default_port: 21640
    owner: was6u500
    group: was6group
    path: /data/pch/{{ was_app_name }}

    systemProperties:
    - name: logback.configurationFile
      value: "{{ path }}/resources/logback.xml"
    - name: spring.profiles.active
      value: bcmpch.managed
    - name: bcmpch.environment
      value: INTEG   
    - name: jms.login
      value: mqm

      
    vhost: BCMPCH_500_vhost
    host_aliases:
    - hostname:  s598li2wseb01.integ.gfdi.be
      port: 21640

    jmscf:
    - jndiName: jms/BCMPCH_mqConnectionFactory
      qmgrName: NQM5EB1
      qmgrSvrconnChannel: MTEAM.CLIENT.SVRCONN
      connectionNameList: s598li2iib03.integ.gfdi.be(15500)
      authDataAlias: JMSCF/uqmeb500
      user: uqmeb500
      authDataPassword: n3touc3p4s4s4
      name: BCMPCH_mqConnectionFactory
      connectionPool:
        minConnections: 1
        maxConnections: 100
      sessionPool:
        minConnections: 1
        maxConnections: 10

            
    dataSources:
      - authDataAlias: udbbl25105/dbpch500
        user: dbpch500
        authDataPassword: 500irucn
        currentSchema: BCMPCH
        databaseName: FIN500
        driverType: 4
        jndiName: jdbc/BCMPCH
        name: BCMPCH_INTEG
        portNumber: 50004
        serverName: s998li2dbfn01.integ.gfdi.be
        typeds: universal
        webSphereDefaultIsolationLevel: 2
        enableRowsetSupport: 1
        connectionPool:
           minConnections: 1
           maxConnections: 10         

    resourceFiles:
    - files/BCMPCH/logback.xml
    
  roles:
  - base_was



  tasks:
  - name: create mteam directory 
    file: path="/mteam" state=directory owner={{ owner }} group={{ group }} mode=0775  
  - name: create bcmpch sub directory for bcmpchBatch
    file: path="/mteam/bcmpch" state=directory owner={{ owner }} group={{ group }} mode=0777
  - name: create pdf-work-scriptura directory 
    file: path="/data/pch/pdf-work-scriptura" state=directory owner={{ owner }} group={{ group }} mode=0775  
  - name: create link wpprintdocs
    file: src="/eBusiness/wppdocs" dest="/mteam/bcmpch/wpprintdocs" state=link
  - name: create link bcmpch
    file: src="/eBusiness/bcmpch" dest="/mteam/bcmpch/bcmpch-share" state=link
  - name: create link pdf-work-scriptura
    file: src="/data/pch/pdf-work-scriptura" dest="/mteam/bcmpch/pdf-work-scriptura" state=link