---
- hosts: RefNodeapps501
  user: root
  vars:
    was_app_name: EBP506_apps5
    default_port: 21180
    owner: was6u500
    group: was6group
    path: /data/ebp/{{ was_app_name }}

    dataSources:
    - authDataAlias: REF/EBP506
      user: EBP506
      authDataPassword: EBP506
      dataTruncation: 'false'
      databaseName: REFGFDI
      dateFormat: iso
      jndiName: jdbc/EBP_506
      libraries: '*LIBL'
      name: AS400EBP_506
      naming: system
      serverName: ref.ref.cpc998.be
      timeFormat: iso
      typeds: toolbox

    host_aliases:
    - hostname: ebp506-ref.ref.cpc998.be
      port: 80

    directories:
    - "{{ path }}/work/in"
    - "{{ path }}/work/in/archive"
    - "{{ path }}/work/in/archive/deliveryreport"
    - "{{ path }}/work/in/archive/ndcdeliveryreport"
    - "{{ path }}/work/in/archive/optinreport"
    - "{{ path }}/work/in/deliveryreport"
    - "{{ path }}/work/in/ndcdeliveryreport"
    - "{{ path }}/work/in/optinreport"
    - "{{ path }}/work/logs"
    - "{{ path }}/work/out"
    - "{{ path }}/work/out/archive"
    - "{{ path }}/work/out/pdf"
    - "{{ path }}/work/out/xml"
    - "{{ path }}/work/out/zip"

    resourceFiles:
    - files/EBP506/ebp_506.properties
    - files/EBP506/id_dsa
    - files/EBP506/logback.xml

    systemProperties:
    - name: spring.profiles.active
      value: prod
    - name: ebp.configuration.file
      value: "{{ path }}/resources/ebp_506.properties"
    - name: logback.configurationFile
      value: "{{ path }}/resources/logback.xml"

  roles:
  - base_was
